### ISSUE TITLE
lsl_viewer main not working

### ISSUE THREAD

**Issue by rajshekarreddy97** [intheon/stream_viewer#3]
Hello, any idea how to fix the below issue?

Traceback (most recent call last):
  File "C:\Users\xxxx\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\stream_viewer\data\stream_info.py", line 99, in refresh
    self._data = self._data.append(new_df.drop(columns=['_merge']), ignore_index=True)
  File "C:\Users\xxxx\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\pandas\core\generic.py", line 5989, in __getattr__
    return object.__getattribute__(self, name)
AttributeError: 'DataFrame' object has no attribute 'append'

I get the above error whenever I run 
python3 -m stream_viewer.applications.main in cmd. I'm new to python and I'm not sure what this means. Any help is appreciated. I do have all the packages installed.

**Comment by insane-dreamer** [comment]
The latest version of the pandas library breaks backward compatibility with some function calls used in lsl_viewer. We'll update the conda requirements file to lock pandas to version 1.5.x., but in the meantime you can  resolve this by changing the `pandas` line to `pandas=1.5.*` in your `conda-requirements.yml` file and then recreating the conda environment.

**Comment by insane-dreamer** [comment]
The latest version of `pandas` breaks backward compatibility with some function calls used in `lsl_viewer`. You can resolve this by updating your conda environment to install `pandas=1.5.*`, or we just merged in a pull request that updates the `conda-environment.yml` and locks `pandas` to `<2.0`, so you can also pull the repo and then create a new conda environment from the updated `conda-environment.yml`

**Comment by rajshekarreddy97** [comment]
I'll give this a shot! Thanks a bunch!

**Comment by amar-enkhbat** [comment]
@insane-dreamer @rajshekarreddy97 
I'm experiencing the same issue. I attempted to downgrade Pandas and NumPy, but now I'm encountering different errors. Could you please share the Python version and dependency versions that work correctly?

**Comment by insane-dreamer** [comment]
@amar-enkhbat the code has been updated to be compatible with pandas >= 2.0 so you shouldn't get this error anymore.
